export function automationManagerSource(_spec, _snapshot, operations = {}) {
  const detailEnabled = operations.detail?.enabled === true;
  const canCreate = operations.create?.enabled === true;
  const canUpdate = operations.update?.enabled === true;
  const canDelete = operations.delete?.enabled === true;
  const editorImport = canCreate || canUpdate ? `import { AutomationEditor } from "./automation-editor";\n` : "";
  return `${editorImport}import { AlertTriangle, ArrowLeft, CalendarDays, CheckCircle2, ChevronRight, CircleSlash2, Clock3, GitBranch, LoaderCircle, Pencil, Plus, Power, RefreshCw, Search, TimerReset, Trash2, Workflow, X, XCircle, Zap } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { AutomationCapabilityRegistry, AutomationCondition, AutomationDetail, AutomationDraft, AutomationItem, AutomationOperationResult, AutomationRuleAction } from "../../runtime/use-automations";

type Feedback = { type: "success" | "error"; message: string };
type Props = { automations: AutomationItem[]; loading: boolean; toggle: (automation: AutomationItem) => Promise<boolean>; activeRoute?: string; onNavigate?: (route: string) => void; details?: Record<string, AutomationDetail>; detailLoading?: Record<string, boolean>; detailErrors?: Record<string, string>; loadDetail?: (automationId: string, force?: boolean) => Promise<AutomationDetail | undefined>; registry?: AutomationCapabilityRegistry; registryLoading?: boolean; registryError?: string; detailUnavailableReason?: string; previewCreate?: (draft: AutomationDraft) => Promise<AutomationOperationResult>; createAutomation?: (draft: AutomationDraft) => Promise<AutomationOperationResult>; previewUpdate?: (automationId: string, draft: AutomationDraft) => Promise<AutomationOperationResult>; updateAutomation?: (automationId: string, draft: AutomationDraft) => Promise<AutomationOperationResult>; previewDelete?: (automation: AutomationItem) => Promise<AutomationOperationResult>; deleteAutomation?: (automation: AutomationItem) => Promise<string> };
const repeatLabels: Record<string, string> = { once: "仅一次", daily: "每天", weekdays: "工作日", weekend: "周末", legal_holiday: "法定节假日", legal_workday: "法定工作日" };
const propertyLabels: Record<string, string> = { power: "开关", brightness: "亮度", colorTemperature: "色温", color: "颜色", targetPercent: "开合度", switchPower: "回路开关", temperature: "温度", humidity: "湿度", occupancy: "有人状态", contact: "门窗状态", pm25: "PM2.5", co2: "二氧化碳", online: "在线状态" };
const eventLabels: Record<string, string> = { "presence.detected": "检测到有人", "presence.clear": "区域无人", "contact.open": "门窗打开", "water.detected": "检测到水浸", "panel.away": "面板离家", "smoke.detected": "检测到烟雾" };
const operationLabels: Record<string, string> = { eq: "等于", gt: "高于", gte: "不低于", lt: "低于", lte: "不高于" };

export function AutomationManager(props: Props) {
  const { automations, loading, activeRoute = "automations", onNavigate = () => {}, details = {}, detailLoading = {}, detailErrors = {}, loadDetail, registry = { targets: {}, supported: [], supportedV2: [] } } = props;
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all");
  const openerRefs = useRef<Record<string, HTMLButtonElement | null>>({}); const previousActiveId = useRef("");
  const routeParts = activeRoute.split("/"); const isCreate = routeParts[1] === "new"; const isEditor = isCreate || routeParts[2] === "edit"; const activeId = isCreate ? "" : routeParts[1] || ""; const selected = automations.find((item) => item.id === activeId); const detail = details[activeId];
  const filtered = useMemo(() => automations.filter((item) => (status === "all" || (status === "enabled") === item.enabled) && (!query.trim() || item.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))), [automations, query, status]);
  useEffect(() => { if (activeId && loadDetail) void loadDetail(activeId); }, [activeId]);
  useEffect(() => { if (activeId && detail) requestAnimationFrame(() => document.querySelector<HTMLElement>("#automation-detail-title")?.focus()); }, [activeId, detail]);
  useEffect(() => { const previous = previousActiveId.current; previousActiveId.current = activeId; if (!activeId && previous) requestAnimationFrame(() => openerRefs.current[previous]?.focus()); }, [activeId]);
  const openDetail = (item: AutomationItem, trigger: HTMLButtonElement) => { openerRefs.current[item.id] = trigger; onNavigate("automations/" + item.id); };

  return isEditor ? <AutomationEditor mode={isCreate ? "create" : "update"} automation={detail} registry={registry} onPreview={isCreate ? props.previewCreate! : (draft) => props.previewUpdate!(activeId, draft)} onSave={isCreate ? props.createAutomation! : (draft) => props.updateAutomation!(activeId, draft)} onCancel={() => onNavigate(isCreate ? "automations" : "automations/" + activeId)} onNavigate={onNavigate} /> : <section className={${detailEnabled} ? "automation-module automation-directory" : "automation-module automation-directory no-detail"} aria-labelledby="automation-title" data-automation-view={activeId ? "detail" : "list"}>
    <div className="automation-master"><div className="section-heading automation-heading"><div><span className="eyebrow">规则运行</span><h2 id="automation-title" tabIndex={-1}>家庭自动化</h2><p>查看触发逻辑与执行范围，并管理规则状态。</p></div><div className="automation-heading-actions"><span className="automation-count">{filtered.length} / {automations.length}</span>${canCreate ? `<button type="button" className="automation-create-button" onClick={() => onNavigate("automations/new")}><Plus size={17} />新建自动化</button>` : ""}</div></div>
      <div className="automation-filters"><label className="search-field"><span>搜索自动化</span><span className="search-input"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="规则名称" /></span></label><label><span>状态</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">全部状态</option><option value="enabled">已启用</option><option value="disabled">已停用</option></select></label></div>
      {props.detailUnavailableReason && <div className="automation-boundary"><CircleSlash2 size={18} /><span>{props.detailUnavailableReason}</span></div>}
      <div className="automation-list" aria-busy={loading}>{filtered.map((item) => <AutomationRow key={item.id} item={item} toggle={props.toggle} selected={item.id === activeId} open={(trigger) => openDetail(item, trigger)} openerRef={(node) => { openerRefs.current[item.id] = node; }} detailEnabled={${detailEnabled}} />)}{!loading && filtered.length === 0 && <div className="empty-state"><Search size={20} /><strong>没有符合条件的自动化</strong><span>调整搜索词或状态筛选。</span></div>}</div>
    </div>
    {${detailEnabled} && <div className="automation-detail-pane">{activeId ? <AutomationDetailView item={selected} detail={detail} loading={detailLoading[activeId] === true} error={detailErrors[activeId]} retry={() => loadDetail?.(activeId, true)} back={() => onNavigate("automations")} toggle={props.toggle} registry={registry} registryLoading={props.registryLoading} registryError={props.registryError} onNavigate={onNavigate} previewDelete={props.previewDelete} deleteAutomation={props.deleteAutomation} /> : <div className="automation-detail-empty"><Workflow size={24} /><strong>选择一条自动化查看详情</strong><span>触发条件、有效时段和执行动作会显示在这里。</span></div>}</div>}
  </section>;
}

function AutomationRow({ item, toggle, selected, open, openerRef, detailEnabled }: { item: AutomationItem; toggle: Props["toggle"]; selected: boolean; open: (trigger: HTMLButtonElement) => void; openerRef: (node: HTMLButtonElement | null) => void; detailEnabled: boolean }) {
  const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState<Feedback>(); const intent = item.enabled ? "automation.disable" : "automation.enable"; const proven = item.actions.some((action) => action.intent === intent && action.evidence === "preview-only");
  const change = async () => { setBusy(true); setFeedback(undefined); try { const enabled = await toggle(item); setFeedback({ type: "success", message: enabled ? "已启用" : "已停用" }); } catch (cause) { setFeedback({ type: "error", message: cause instanceof Error ? cause.message : "状态更新失败，请重试。" }); } finally { setBusy(false); } };
  return <article className={selected ? "automation-row selected" : "automation-row"}><button ref={openerRef} type="button" className="automation-open-button" disabled={!detailEnabled} onClick={(event) => open(event.currentTarget)} aria-current={selected ? "page" : undefined}><span className={item.enabled ? "automation-icon enabled" : "automation-icon"}><Workflow size={20} /></span><span className="automation-copy"><strong>{item.name}</strong><small>{item.enabled ? "运行中" : "已停用"}</small></span>{detailEnabled && <ChevronRight size={18} />}</button>{proven ? <button type="button" className={item.enabled ? "automation-switch on" : "automation-switch"} role="switch" aria-checked={item.enabled} aria-label={(item.enabled ? "停用" : "启用") + item.name} disabled={busy} onClick={() => void change()}>{busy ? <LoaderCircle className="spin" size={18} /> : <span aria-hidden="true" />}</button> : <span className="automation-unavailable"><CircleSlash2 size={17} />只读</span>}<div className={feedback ? "automation-feedback " + feedback.type : "automation-feedback"} aria-live="polite">{feedback ? <>{feedback.type === "success" ? <CheckCircle2 size={16} /> : <XCircle size={16} />}<span>{feedback.message}</span></> : null}</div></article>;
}

function AutomationDetailView({ item, detail, loading, error, retry, back, toggle, registry, registryLoading, registryError, onNavigate, previewDelete, deleteAutomation }: { item?: AutomationItem; detail?: AutomationDetail; loading: boolean; error?: string; retry: () => void; back: () => void; toggle: Props["toggle"]; registry: AutomationCapabilityRegistry; registryLoading?: boolean; registryError?: string; onNavigate: Props["onNavigate"]; previewDelete?: Props["previewDelete"]; deleteAutomation?: Props["deleteAutomation"] }) {
  const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState<Feedback>(); const [deleteOpen, setDeleteOpen] = useState(false); const resolved = detail || item; const conditions = detail?.trigger ? ("conditions" in detail.trigger ? detail.trigger.conditions : [detail.trigger]) : detail?.conditions || []; const actions = detail?.ruleActions || []; const statusIntent = resolved?.enabled ? "automation.disable" : "automation.enable"; const statusProven = resolved?.actions.some((action) => action.intent === statusIntent && action.evidence === "preview-only") === true;
  const change = async () => { if (!resolved) return; setBusy(true); setFeedback(undefined); try { const enabled = await toggle(resolved); setFeedback({ type: "success", message: enabled ? "自动化已启用" : "自动化已停用" }); } catch (cause) { setFeedback({ type: "error", message: cause instanceof Error ? cause.message : "状态更新失败，请重试。" }); } finally { setBusy(false); } };
  return <section className="automation-detail" aria-busy={loading}><header><button type="button" className="automation-back-button" onClick={back}><ArrowLeft size={18} />返回自动化</button><div><span className="eyebrow">{resolved?.enabled ? "运行中" : "已停用"}</span><h2 id="automation-detail-title" tabIndex={-1}>{resolved?.name || "自动化详情"}</h2><p>{logicSummary(detail, conditions.length)}</p></div></header>
    {error ? <div className="automation-detail-error" role="alert"><XCircle size={20} /><div><strong>此自动化详情暂时不可用</strong><span>{error} 列表和状态管理仍可使用。</span></div><button type="button" onClick={retry}><RefreshCw size={17} />重试</button></div> : loading && !detail ? <div className="automation-detail-loading"><LoaderCircle className="spin" size={22} />正在同步规则详情</div> : detail ? <><div className="automation-schedule-grid"><span><Clock3 size={17} /><small>有效时段</small><strong>{formatWindow(detail.activeWindow)}</strong></span><span><CalendarDays size={17} /><small>重复</small><strong>{formatRepeat(detail.repeat)}</strong></span><span><TimerReset size={17} /><small>规则版本</small><strong>V{detail.version || "-"}</strong></span></div>
      <RuleSection icon={<GitBranch size={18} />} eyebrow="当满足条件" title={detail.conditionType === "or" ? "任一条件成立" : detail.conditionType === "and" ? "全部条件成立" : "触发条件"} count={conditions.length}>{conditions.map((condition, index) => <ConditionRow key={index} condition={condition} index={index} registry={registry} />)}</RuleSection>
      <RuleSection icon={<Zap size={18} />} eyebrow="则执行" title="动作摘要" count={actions.length}>{actions.map((action, index) => <ActionRow key={index} action={action} index={index} />)}</RuleSection>
      {registryLoading && <p className="automation-registry-state">正在匹配家庭设备的条件能力。</p>}{registryError && <p className="automation-registry-warning">部分条件名称暂时无法同步，规则原始语义已保留。</p>}</> : null}
    {resolved && <><footer className="automation-detail-actions">{statusProven ? <button type="button" className={resolved.enabled ? "automation-status-button stop" : "automation-status-button"} disabled={busy} onClick={() => void change()}>{busy ? <LoaderCircle className="spin" size={18} /> : <Power size={18} />}{resolved.enabled ? "停用自动化" : "启用自动化"}</button> : <span className="automation-detail-readonly"><CircleSlash2 size={18} />当前家庭仅支持查看此自动化</span>}${canUpdate ? `{detail && <button type="button" className="secondary-button" onClick={() => onNavigate?.("automations/" + resolved.id + "/edit")}><Pencil size={17} />编辑自动化</button>}` : ""}{feedback && <div className={"automation-feedback detail " + feedback.type} aria-live="polite">{feedback.type === "success" ? <CheckCircle2 size={16} /> : <XCircle size={16} />}<span>{feedback.message}</span></div>}</footer>${canDelete ? `<section className="automation-danger-zone"><div><small>危险操作</small><h3>删除自动化</h3><p>删除后规则不会再触发，且无法撤销。</p></div><button type="button" className="danger-link" onClick={() => setDeleteOpen(true)}><Trash2 size={17} />删除自动化</button></section>{deleteOpen && item && <GuardedAutomationDelete automation={item} close={() => setDeleteOpen(false)} previewDelete={previewDelete!} deleteAutomation={deleteAutomation!} done={() => onNavigate?.("automations")} />}` : ""}</>}
  </section>;
}

${canDelete ? `function GuardedAutomationDelete({ automation, close, previewDelete, deleteAutomation, done }: { automation: AutomationItem; close: () => void; previewDelete: NonNullable<Props["previewDelete"]>; deleteAutomation: NonNullable<Props["deleteAutomation"]>; done: () => void }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const confirm = async () => { setBusy(true); setError(""); try { await previewDelete(automation); await deleteAutomation(automation); close(); done(); } catch (cause) { setError(cause instanceof Error ? cause.message : "删除失败，自动化仍然保留。"); } finally { setBusy(false); } }; return <div className="automation-delete-backdrop"><section className="automation-delete-dialog" role="dialog" aria-modal="true" aria-labelledby="automation-delete-title"><header><AlertTriangle size={22} /><div><small>不可恢复</small><h3 id="automation-delete-title">删除“{automation.name}”</h3></div><button type="button" className="icon-button" disabled={busy} onClick={close} aria-label="关闭删除确认"><X size={18} /></button></header><p>系统会先预览影响，再执行删除，并通过自动化列表确认该规则已经不存在。</p>{error && <div className="field-error" role="alert">{error}</div>}<footer><button type="button" className="secondary-button" disabled={busy} onClick={close}>取消</button><button type="button" className="danger-button" disabled={busy} onClick={() => void confirm()}>{busy ? <LoaderCircle className="spin" size={17} /> : <Trash2 size={17} />}{busy ? "正在验证删除" : "确认删除"}</button></footer></section></div>; }` : ""}

function RuleSection({ icon, eyebrow, title, count, children }: { icon: React.ReactNode; eyebrow: string; title: string; count: number; children: React.ReactNode }) { return <section className="automation-rule-section"><div className="automation-subheading"><span>{icon}</span><div><small>{eyebrow}</small><h3>{title}</h3></div><b>{count} 项</b></div><div className="automation-rule-list">{children}</div></section>; }
function ConditionRow({ condition, index, registry }: { condition: AutomationCondition; index: number; registry: AutomationCapabilityRegistry }) { const target = condition.targetId ? registry.targets[condition.targetId] : undefined; return <div className="automation-rule-row"><span>{index + 1}</span><div><strong>{condition.conditionKind === "alarm" ? "定时" : target?.name || "设备条件"}</strong><small>{target?.roomName || conditionTypeLabel(condition.conditionKind)}</small><p>{conditionText(condition)}</p></div></div>; }
function ActionRow({ action, index }: { action: AutomationRuleAction; index: number }) { return <div className="automation-rule-row"><span>{index + 1}</span><div><strong>{action.targetName || "执行对象"}</strong><small>{targetTypeLabel(action.targetType)}</small><p>{action.action === "execute" ? "执行情景" : Object.entries(action.set || {}).map(([key, value]) => (propertyLabels[key] || key) + "：" + formatValue(key, value)).join(" · ") || "执行已配置动作"}</p></div></div>; }
function logicSummary(detail: AutomationDetail | undefined, count: number) { if (!detail) return "正在读取触发条件与执行动作。"; if (detail.conditionType === "or") return count + " 个条件，任一满足时执行"; if (detail.conditionType === "and") return count + " 个条件，全部满足时执行"; return "单一触发条件，满足后执行"; }
function conditionText(condition: AutomationCondition) { if (condition.conditionKind === "alarm") return "每天 " + String(condition.time || "--:--").slice(0, 5); if (condition.conditionKind === "event") return eventLabels[condition.event || ""] || "发生设备事件"; const property = propertyLabels[condition.property || ""] || condition.property || "属性"; if (condition.conditionKind === "fact_change") return property + "变为 " + formatValue(condition.property || "", condition.value); return property + " " + (operationLabels[condition.operation || ""] || condition.operation || "满足") + " " + formatValue(condition.property || "", condition.value); }
function conditionTypeLabel(kind?: string) { return ({ event: "设备事件", fact: "属性阈值", fact_change: "属性变化" } as Record<string, string>)[kind || ""] || "触发条件"; }
function targetTypeLabel(type?: string) { return ({ device: "设备", group: "设备组", meshGroup: "设备组", room: "房间", scene: "情景" } as Record<string, string>)[type || ""] || "家庭对象"; }
function formatWindow(window?: { start?: string; end?: string }) { return window ? String(window.start || "00:00").slice(0, 5) + " - " + String(window.end || "23:59").slice(0, 5) : "全天"; }
function formatRepeat(value?: string | Record<string, unknown>) { return typeof value === "string" ? repeatLabels[value] || value : value ? "自定义" : "未设置"; }
function formatValue(key: string, value: unknown) { if (typeof value === "boolean") return value ? "开启" : "关闭"; if (key === "brightness" || key === "targetPercent" || key === "humidity") return value + "%"; if (key === "colorTemperature") return value + " K"; if (key === "temperature") return value + "°C"; if (key === "co2") return value + " ppm"; if (key === "pm25") return value + " μg/m³"; return String(value ?? "-"); }
`;
}
