export function automationEditorSource() {
  return `import { ArrowLeft, ArrowRight, Check, CircleAlert, LoaderCircle, Plus, Save, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { AutomationCapabilityRegistry, AutomationCondition, AutomationDetail, AutomationDraft, AutomationOperationResult, AutomationRuleAction, AutomationTrigger } from "../../runtime/use-automations";
import { useUnsavedNavigationGuard } from "../../runtime/use-unsaved-navigation-guard";

type Props = { mode: "create" | "update"; automation?: AutomationDetail; registry: AutomationCapabilityRegistry; onPreview: (draft: AutomationDraft) => Promise<AutomationOperationResult>; onSave: (draft: AutomationDraft) => Promise<AutomationOperationResult>; onCancel: () => void; onNavigate: (route: string) => void };
type Issue = { field: string; message: string };
const steps = ["基本信息", "触发方式", "条件", "执行动作", "检查并保存"];
const properties: Record<string, string> = { power: "开关", brightness: "亮度", colorTemperature: "色温", targetPercent: "开合度", switchPower: "回路开关", temperature: "温度", humidity: "湿度", occupancy: "有人状态", contact: "门窗状态", pm25: "PM2.5", co2: "二氧化碳", online: "在线状态" };

export function AutomationEditor({ mode, automation, registry, onPreview, onSave, onCancel, onNavigate }: Props) {
  const initial = useMemo(() => automationDraft(automation), [automation]);
  const [draft, setDraft] = useState(initial); const [step, setStep] = useState(0); const [issues, setIssues] = useState<Issue[]>([]); const [busy, setBusy] = useState<"preview" | "save" | "">(""); const [feedback, setFeedback] = useState("");
  const dirty = JSON.stringify(draft) !== JSON.stringify(initial);
  const guard = useUnsavedNavigationGuard({ dirty, onCancel, onNavigate, fallbackFocusSelector: "#automation-field-name, .automation-back-button" });
  useEffect(() => { setDraft(initial); }, [initial]);
  useEffect(() => { document.querySelector<HTMLElement>(".shell-content")?.scrollTo({ top: 0 }); requestAnimationFrame(() => document.querySelector<HTMLElement>("#automation-editor-title")?.focus()); }, []);
  const goNext = () => { const nextIssues = validateStep(draft, step); setIssues(nextIssues); if (nextIssues.length) return focusIssue(nextIssues[0]); setStep((value) => Math.min(4, value + 1)); };
  const save = async () => { const all = validateDraft(draft); setIssues(all); if (all.length) { setStep(stepFor(all[0].field)); return focusIssue(all[0]); } setBusy("preview"); setFeedback(""); try { await onPreview(draft); setBusy("save"); const result = await onSave(draft); setFeedback(result.message || "自动化已保存"); guard.allowNavigate(result.automationId ? "automations/" + result.automationId : automation ? "automations/" + automation.id : "automations"); } catch (cause) { setFeedback(cause instanceof Error ? cause.message : "保存失败，当前更改已保留，请重试。"); } finally { setBusy(""); } };
  return <section className="automation-editor" data-unsaved-editor aria-labelledby="automation-editor-title" aria-busy={Boolean(busy)}>
    <header className="automation-editor-header"><button type="button" className="automation-back-button" onClick={guard.requestCancel}><ArrowLeft size={18} />取消</button><div><span className="eyebrow">{mode === "create" ? "新建自动化" : "编辑自动化"}</span><h2 id="automation-editor-title" tabIndex={-1}>{draft.name || "未命名自动化"}</h2></div><span>{step + 1} / 5</span></header>
    <nav className="automation-stepper" aria-label="自动化编辑步骤">{steps.map((label, index) => <button type="button" key={label} aria-current={step === index ? "step" : undefined} disabled={index > step + 1 || Boolean(busy)} onClick={() => setStep(index)}><span>{index < step ? <Check size={15} /> : index + 1}</span><strong>{label}</strong></button>)}</nav>
    <div className="automation-step-summary"><span>步骤 {step + 1} / 5</span><strong>{steps[step]}</strong></div>
    <div className="automation-editor-body">{step === 0 ? <Basics draft={draft} issues={issues} update={setDraft} /> : step === 1 ? <Trigger draft={draft} registry={registry} issues={issues} update={setDraft} /> : step === 2 ? <Conditions draft={draft} registry={registry} update={setDraft} /> : step === 3 ? <Actions draft={draft} registry={registry} issues={issues} update={setDraft} /> : <Review draft={draft} />}</div>
    {feedback && <div className="automation-editor-feedback" role="status"><CircleAlert size={17} /><span>{feedback}</span></div>}
    <footer className="automation-editor-footer"><button type="button" className="secondary-button" disabled={step === 0 || Boolean(busy)} onClick={() => setStep((value) => value - 1)}><ArrowLeft size={17} />上一步</button>{step < 4 ? <button type="button" className="primary-button" disabled={Boolean(busy)} onClick={goNext}>下一步<ArrowRight size={17} /></button> : <button type="button" className="primary-button" disabled={Boolean(busy)} onClick={() => void save()}>{busy ? <LoaderCircle className="spin" size={17} /> : <Save size={17} />}{busy === "preview" ? "正在预览" : busy === "save" ? "正在保存" : "预览并保存"}</button>}</footer>
    {guard.open && <div className="automation-guard-backdrop"><section ref={guard.dialogRef} className="automation-guard-dialog" role="dialog" aria-modal="true" aria-labelledby="automation-guard-title" tabIndex={-1}><header><div><small>尚未保存</small><h3 id="automation-guard-title">保留当前更改？</h3></div></header><p>离开后，本次自动化配置不会保存。</p><footer><button type="button" className="secondary-button" data-autofocus onClick={guard.continueEditing}>继续编辑</button><button type="button" className="danger-button" onClick={guard.discard}>放弃更改</button><button type="button" className="ghost-button" onClick={guard.continueEditing}>取消离开</button></footer></section></div>}
  </section>;
}

function Basics({ draft, issues, update }: { draft: AutomationDraft; issues: Issue[]; update: React.Dispatch<React.SetStateAction<AutomationDraft>> }) { return <div className="automation-editor-section"><div><span className="eyebrow">规则身份</span><h3>基本信息与生效范围</h3><p>名称用于快速识别；有效时段限制规则每天可运行的时间。</p></div><label htmlFor="automation-field-name">自动化名称<input id="automation-field-name" value={draft.name} aria-invalid={has(issues, "name")} onChange={(event) => update((value) => ({ ...value, name: event.target.value }))} />{message(issues, "name") && <span className="field-error">{message(issues, "name")}</span>}</label><div className="automation-field-grid"><label>开始时间<input type="time" step="1" value={draft.activeWindow.start} onChange={(event) => update((value) => ({ ...value, activeWindow: { ...value.activeWindow, start: event.target.value } }))} /></label><label>结束时间<input type="time" step="1" value={draft.activeWindow.end} onChange={(event) => update((value) => ({ ...value, activeWindow: { ...value.activeWindow, end: event.target.value } }))} /></label><label>重复<select value={String(draft.repeat)} onChange={(event) => update((value) => ({ ...value, repeat: event.target.value }))}><option value="once">仅一次</option><option value="daily">每天</option><option value="weekdays">工作日</option><option value="weekends">周末</option></select></label></div></div>; }

function Trigger({ draft, registry, issues, update }: { draft: AutomationDraft; registry: AutomationCapabilityRegistry; issues: Issue[]; update: React.Dispatch<React.SetStateAction<AutomationDraft>> }) { const trigger = firstCondition(draft.trigger); return <div className="automation-editor-section"><div><span className="eyebrow">何时开始</span><h3>触发方式</h3><p>触发源来自当前家庭与 Runtime 返回的公开能力。</p></div><label>类型<select value={trigger.conditionKind || "alarm"} onChange={(event) => update((value) => ({ ...value, trigger: defaultCondition(event.target.value, registry) }))}><option value="alarm">定时</option><option value="event">设备事件</option><option value="fact">属性阈值</option><option value="fact_change">属性变化</option></select></label>{trigger.conditionKind === "alarm" ? <label htmlFor="automation-field-trigger">触发时间<input id="automation-field-trigger" type="time" step="1" value={trigger.time || "07:00:00"} onChange={(event) => update((value) => ({ ...value, trigger: { ...trigger, time: event.target.value } }))} />{message(issues, "trigger") && <span className="field-error">{message(issues, "trigger")}</span>}</label> : <ConditionFields condition={trigger} registry={registry} change={(condition) => update((value) => ({ ...value, trigger: condition }))} />}</div>; }

function Conditions({ draft, registry, update }: { draft: AutomationDraft; registry: AutomationCapabilityRegistry; update: React.Dispatch<React.SetStateAction<AutomationDraft>> }) { const group = isGroup(draft.trigger) ? draft.trigger : { conditionType: "and" as const, conditions: [draft.trigger] }; return <div className="automation-editor-section"><div><span className="eyebrow">组合逻辑</span><h3>条件</h3><p>单条件可直接运行；多个条件可按全部满足或任一满足组合。</p></div><label>组合方式<select value={group.conditionType} onChange={(event) => update((value) => ({ ...value, trigger: { ...group, conditionType: event.target.value as "and" | "or" } }))}><option value="and">全部条件满足</option><option value="or">任一条件满足</option></select></label><div className="automation-condition-edit-list">{group.conditions.map((condition, index) => <div className="automation-condition-edit" key={index}><span>{index + 1}</span><ConditionFields condition={condition} registry={registry} change={(next) => update((value) => ({ ...value, trigger: { ...group, conditions: group.conditions.map((item, itemIndex) => itemIndex === index ? next : item) } }))} />{group.conditions.length > 1 && <button type="button" className="icon-button" aria-label={"删除条件 " + (index + 1)} onClick={() => update((value) => ({ ...value, trigger: { ...group, conditions: group.conditions.filter((_, itemIndex) => itemIndex !== index) } }))}><Trash2 size={17} /></button>}</div>)}</div><button type="button" className="secondary-button" onClick={() => update((value) => ({ ...value, trigger: { ...group, conditions: [...group.conditions, defaultCondition("fact", registry)] } }))}><Plus size={17} />添加条件</button></div>; }

function Actions({ draft, registry, issues, update }: { draft: AutomationDraft; registry: AutomationCapabilityRegistry; issues: Issue[]; update: React.Dispatch<React.SetStateAction<AutomationDraft>> }) { const targets = Object.values(registry.targets).filter((item) => item.writableProperties.length); return <div className="automation-editor-section"><div><span className="eyebrow">规则结果</span><h3>执行动作</h3><p>仅显示已从家庭实体与控制证据中发现的公开属性。</p></div>{draft.actions.map((action, index) => { const target = registry.targets[String(action.targetId || "")] || targets[0]; const property = Object.keys(action.set || {})[0] || target?.writableProperties[0] || "power"; return <div className="automation-action-edit" key={index}><span>{index + 1}</span><label>目标<select value={String(action.targetId || "")} onChange={(event) => { const selected = registry.targets[event.target.value]; update((value) => ({ ...value, actions: value.actions.map((item, itemIndex) => itemIndex === index ? actionFor(selected) : item) })); }}>{targets.map((item) => <option key={item.id} value={item.id}>{item.name}{item.roomName ? " · " + item.roomName : ""}</option>)}</select></label><label>属性<select value={property} onChange={(event) => update((value) => ({ ...value, actions: value.actions.map((item, itemIndex) => itemIndex === index ? { ...item, set: { [event.target.value]: defaultValue(event.target.value) } } : item) }))}>{(target?.writableProperties || []).map((item) => <option key={item} value={item}>{properties[item] || item}</option>)}</select></label><label>目标值<input value={String(action.set?.[property] ?? "")} onChange={(event) => update((value) => ({ ...value, actions: value.actions.map((item, itemIndex) => itemIndex === index ? { ...item, set: { [property]: parseValue(property, event.target.value) } } : item) }))} /></label>{draft.actions.length > 1 && <button type="button" className="icon-button" aria-label={"删除动作 " + (index + 1)} onClick={() => update((value) => ({ ...value, actions: value.actions.filter((_, itemIndex) => itemIndex !== index) }))}><Trash2 size={17} /></button>}</div>; })}<button type="button" className="secondary-button" disabled={!targets.length} onClick={() => update((value) => ({ ...value, actions: [...value.actions, actionFor(targets[0])] }))}><Plus size={17} />添加动作</button>{message(issues, "actions") && <span className="field-error">{message(issues, "actions")}</span>}</div>; }

function ConditionFields({ condition, registry, change }: { condition: AutomationCondition; registry: AutomationCapabilityRegistry; change: (condition: AutomationCondition) => void }) { const targets = Object.values(registry.targets); const target = registry.targets[String(condition.targetId || "")] || targets[0]; const events = target?.events || []; return <div className="automation-condition-fields"><label>来源<select value={String(condition.targetId || "")} onChange={(event) => { const selected = registry.targets[event.target.value]; change({ ...condition, targetType: "device", targetId: selected.id, property: selected.properties[0], event: selected.events[0]?.eventId }); }}>{targets.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{condition.conditionKind === "event" ? <label>事件<select value={condition.event || condition.eventId || ""} onChange={(event) => change({ ...condition, event: event.target.value })}>{events.map((item) => <option key={item.eventId} value={item.eventId}>{item.name}</option>)}</select></label> : <><label>属性<select value={condition.property || ""} onChange={(event) => change({ ...condition, property: event.target.value })}>{(target?.properties || []).map((item) => <option key={item} value={item}>{properties[item] || item}</option>)}</select></label>{condition.conditionKind === "fact" && <label>比较<select value={condition.operation || "gt"} onChange={(event) => change({ ...condition, operation: event.target.value })}><option value="gt">高于</option><option value="gte">不低于</option><option value="lt">低于</option><option value="lte">不高于</option><option value="eq">等于</option></select></label>}<label>值<input value={String(condition.value ?? "")} onChange={(event) => change({ ...condition, value: parseValue(condition.property || "", event.target.value) })} /></label></>}</div>; }

function Review({ draft }: { draft: AutomationDraft }) { const conditions = isGroup(draft.trigger) ? draft.trigger.conditions : [draft.trigger]; return <div className="automation-editor-section automation-review"><div><span className="eyebrow">提交前检查</span><h3>{draft.name}</h3><p>{draft.activeWindow.start} - {draft.activeWindow.end} · {repeatLabel(draft.repeat)}</p></div><section><small>触发与条件</small><strong>{conditions.length} 项 · {isGroup(draft.trigger) ? draft.trigger.conditionType === "or" ? "任一条件成立" : "全部条件成立" : "单一条件"}</strong>{conditions.map((condition, index) => <span key={index}>{conditionSummary(condition)}</span>)}</section><section><small>执行动作</small><strong>{draft.actions.length} 项</strong>{draft.actions.map((action, index) => <span key={index}>{action.targetName || action.targetId} · {Object.entries(action.set || {}).map(([key, value]) => (properties[key] || key) + "：" + displayValue(value)).join("、")}</span>)}</section></div>; }

function automationDraft(detail?: AutomationDetail): AutomationDraft { const known = new Set(["automationId", "name", "activeWindow", "repeat", "version", "trigger", "conditions", "actions"]); const raw = (detail || {}) as Record<string, unknown>; const preserved = Object.fromEntries(Object.entries(raw).filter(([key]) => !known.has(key) && !["id", "enabled", "ruleActions"].includes(key))); const trigger: AutomationTrigger = detail?.trigger || (detail?.conditions.length ? { conditionType: detail.conditionType || "and", conditions: detail.conditions } : { conditionKind: "alarm", time: "07:00:00" }); return { name: detail?.name || "", activeWindow: { start: detail?.activeWindow?.start || "00:00:00", end: detail?.activeWindow?.end || "23:59:59" }, repeat: detail?.repeat || "daily", version: detail?.version, trigger, actions: detail?.ruleActions?.length ? detail.ruleActions : [], preserved }; }
function defaultCondition(kind: string, registry: AutomationCapabilityRegistry): AutomationCondition { if (kind === "alarm") return { conditionKind: "alarm", time: "07:00:00" }; const target = Object.values(registry.targets)[0]; return { conditionKind: kind, targetType: "device", targetId: target?.id, ...(kind === "event" ? { event: target?.events[0]?.eventId } : { property: target?.properties[0], operation: kind === "fact" ? "gt" : undefined, value: defaultValue(target?.properties[0] || "") }) }; }
function actionFor(target?: AutomationCapabilityRegistry["targets"][string]): AutomationRuleAction { const property = target?.writableProperties[0] || "power"; return { targetType: "device", targetId: target?.id || "", targetName: target?.name || "", set: { [property]: defaultValue(property) } }; }
function firstCondition(trigger: AutomationTrigger) { return isGroup(trigger) ? trigger.conditions[0] || { conditionKind: "alarm", time: "07:00:00" } : trigger; }
function isGroup(trigger: AutomationTrigger): trigger is { conditionType: "and" | "or"; conditions: AutomationCondition[] } { return "conditions" in trigger && Array.isArray(trigger.conditions); }
function validateStep(draft: AutomationDraft, step: number): Issue[] { if (step === 0) return draft.name.trim() ? [] : [{ field: "name", message: "请输入自动化名称。" }]; if (step <= 2) return firstCondition(draft.trigger).conditionKind === "alarm" && !firstCondition(draft.trigger).time ? [{ field: "trigger", message: "请选择触发时间。" }] : []; if (step === 3) return draft.actions.length ? [] : [{ field: "actions", message: "至少添加一个执行动作。" }]; return []; }
function validateDraft(draft: AutomationDraft): Issue[] { return [...validateStep(draft, 0), ...validateStep(draft, 1), ...validateStep(draft, 3)]; }
function stepFor(field: string) { return field === "name" ? 0 : field === "trigger" ? 1 : 3; }
function defaultValue(property: string) { if (["power", "switchPower", "online", "occupancy", "contact"].includes(property)) return true; if (property === "colorTemperature") return 4000; if (["brightness", "targetPercent", "humidity"].includes(property)) return 50; return 0; }
function parseValue(property: string, value: string) { if (["power", "switchPower", "online", "occupancy", "contact"].includes(property)) return ["true", "1", "on", "开启"].includes(value.toLowerCase()); const number = Number(value); return Number.isFinite(number) && value.trim() ? number : value; }
function repeatLabel(value: AutomationDraft["repeat"]) { if (typeof value !== "string") return "自定义重复"; return ({ once: "仅一次", daily: "每天", weekdays: "工作日", weekends: "周末" } as Record<string, string>)[value] || value; }
function conditionSummary(condition: AutomationCondition) { if (condition.conditionKind === "alarm") return "每天 " + String(condition.time || "--:--").slice(0, 5); if (condition.conditionKind === "event") return "设备事件 " + String(condition.event || condition.eventId || ""); return (properties[condition.property || ""] || condition.property || "属性") + (condition.conditionKind === "fact_change" ? " 变为 " : " " + String(condition.operation || "满足") + " ") + String(condition.value ?? ""); }
function displayValue(value: unknown) { return typeof value === "boolean" ? value ? "开启" : "关闭" : String(value); }
function has(issues: Issue[], field: string) { return issues.some((item) => item.field === field); }
function message(issues: Issue[], field: string) { return issues.find((item) => item.field === field)?.message || ""; }
function focusIssue(value: Issue) { requestAnimationFrame(() => document.querySelector<HTMLElement>("#automation-field-" + value.field)?.focus()); }
`;
}
