export function panelManagerSource(_spec, _snapshot, operations = {}) {
  const reasons = Object.fromEntries(Object.entries(operations).map(([name, operation]) => [name, operation.userMessage || "当前家庭仅支持查看，暂不能修改。"]));
  return `import { AlertTriangle, ArrowLeft, CheckCircle2, ChevronRight, CircleSlash2, LayoutPanelTop, LoaderCircle, Pencil, Radio, RefreshCw, RotateCcw, Settings2, SlidersHorizontal, Trash2, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { KnobItem, PanelButton, PanelEvent, PanelItem, TargetOption } from "../../runtime/use-panels";
import { KnobDetail } from "./knob-detail";

type Availability = Record<string, { enabled: boolean; message: string }>;
type Props = { panels: PanelItem[]; knobs: KnobItem[]; targets: TargetOption[]; loading: boolean; saving: boolean; errors: Record<string, string>; feedback: string; availability: Availability; activeRoute: string; onNavigate: (route: string) => void; refresh: () => Promise<void>; loadPanel: (id: string) => Promise<PanelItem>; updateAlias: (panelId: string, buttonId: string, alias: string) => Promise<void>; updateEvent: (panelId: string, event: PanelEvent) => Promise<void>; updateEvents: (panelId: string, events: PanelEvent[]) => Promise<void>; resetEvent: (panelId: string, eventId: string) => Promise<void> };
type Editor = { mode: "alias"; panel: PanelItem; button: PanelButton } | { mode: "event" | "reset"; panel: PanelItem; button: PanelButton; event: PanelEvent } | { mode: "batch"; panel: PanelItem; events: PanelEvent[] };
const reasons = ${JSON.stringify(reasons)};

export function PanelManager(props: Props) {
  const segments = props.activeRoute.split("/"); const knobId = segments[1] === "knobs" ? segments[2] : ""; const panelId = knobId ? "" : segments[1]; const panel = props.panels.find((item) => item.id === panelId);
  useEffect(() => { if (panelId) void props.loadPanel(panelId).catch(() => undefined); }, [panelId]);
  if (knobId) return <KnobDetail knobId={knobId} onNavigate={props.onNavigate} />;
  return panelId ? <PanelDetail {...props} panelId={panelId} panel={panel} /> : <PanelDirectory {...props} />;
}

function PanelDirectory({ panels, knobs, loading, errors, refresh, onNavigate }: Props) {
  const offline = panels.filter((item) => !item.online).length;
  return <section className="panel-module panel-directory" aria-labelledby="panel-title">
    <div className="section-heading panel-heading"><div><span className="eyebrow">墙面交互</span><h2 id="panel-title">墙面面板</h2><p>查看按键类型、事件绑定与可用设置。旋钮保持独立能力终态。</p></div><span className="panel-count">{panels.length} 个面板</span></div>
    <div className="panel-summary"><span><LayoutPanelTop size={19} /><strong>{panels.length}</strong><small>全部面板</small></span><span className={offline ? "attention" : "healthy"}><Radio size={19} /><strong>{offline}</strong><small>离线</small></span><span><SlidersHorizontal size={19} /><strong>{knobs.length}</strong><small>智能旋钮</small></span></div>
    {loading && <div className="panel-loading" role="status"><LoaderCircle className="spin" size={18} />正在同步墙面设备</div>}
    <ErrorNotice message={errors.list || errors.detail} retry={refresh} />
    <div className="panel-list">{panels.map((panel) => <button type="button" className={panel.online ? "panel-row" : "panel-row offline"} key={panel.id} onClick={() => onNavigate("panels/" + panel.id)}><span className="panel-icon"><LayoutPanelTop size={21} /></span><span className="panel-row-copy"><strong>{panel.name}</strong><small>{panel.roomName} · {panel.typeName || "墙面面板"}</small><span>{panel.buttons.length} 个按键 · {panel.buttons.reduce((sum, button) => sum + button.events.length, 0)} 项事件</span></span><span className={panel.online ? "panel-status online" : "panel-status"}>{panel.online ? "在线" : "离线"}</span><ChevronRight size={19} /></button>)}</div>
    {!loading && panels.length === 0 && <div className="empty-state"><LayoutPanelTop size={22} /><strong>当前家庭没有墙面面板</strong><span>添加面板后可在这里查看按键与事件绑定。</span></div>}
    {knobs.length > 0 && <section className="panel-knob-terminal" aria-labelledby="knob-terminal-title"><div><SlidersHorizontal size={20} /><div><h3 id="knob-terminal-title">智能旋钮</h3><p>按实例查看绑定、交互方式与可用设置。</p></div></div><div className="panel-knob-list">{knobs.map((knob) => <button type="button" key={knob.id} onClick={() => onNavigate("panels/knobs/" + knob.id)}><span><strong>{knob.name}</strong><small>{knob.roomName} · {knob.actions.length} 项绑定</small></span><span className={knob.online ? "panel-status online" : "panel-status"}>{knob.online ? "在线" : "离线"}</span><ChevronRight size={18} /></button>)}</div></section>}
  </section>;
}

function PanelDetail(props: Props & { panelId: string; panel?: PanelItem }) {
  const { panelId, panel, errors, onNavigate } = props; const [editor, setEditor] = useState<Editor | null>(null); const [focusKey, setFocusKey] = useState("");
  const open = (next: Editor, key: string) => { setFocusKey(key); setEditor(next); };
  const close = () => { setEditor(null); window.setTimeout(() => document.querySelector<HTMLButtonElement>(\`[data-focus-key="\${focusKey}"]\`)?.focus(), 0); };
  if (!panel) return <section className="panel-detail"><button className="back-link" type="button" onClick={() => onNavigate("panels")}><ArrowLeft size={18} />返回面板</button><ErrorNotice message={errors[panelId + ":detail"] || "暂时无法读取此面板。"} retry={() => props.loadPanel(panelId)} /></section>;
  const events = panel.buttons.flatMap((button) => button.events.map((event) => ({ button, event })));
  return <section className="panel-detail" aria-labelledby="panel-detail-title">
    <header><button className="back-link" type="button" onClick={() => onNavigate("panels")}><ArrowLeft size={18} />返回面板</button><div><span className="eyebrow">面板详情</span><h2 id="panel-detail-title">{panel.name}</h2><p>{panel.roomName}</p></div><span className={panel.online ? "panel-status online" : "panel-status"}>{panel.online ? "在线" : "离线"}</span></header>
    <ErrorNotice message={errors[panelId + ":detail"]} retry={() => props.loadPanel(panelId)} />
    <div className="panel-detail-grid">
      <section className="panel-section"><SectionTitle title="设备身份" icon={<LayoutPanelTop size={19} />} /><dl className="panel-facts"><Fact label="设备类型" value={panel.typeName} /><Fact label="所在空间" value={panel.roomName} /><Fact label="按键数量" value={panel.buttons.length} /><Fact label="事件数量" value={events.length} /></dl></section>
      <section className="panel-section"><SectionTitle title="按键类型" icon={<Settings2 size={19} />} /><ErrorNotice message={errors[panelId + ":type"]} retry={() => props.loadPanel(panelId)} /><div className="panel-type-list">{panel.buttons.map((button) => <span key={button.id}><strong>{button.alias}</strong><small>{button.name} · {buttonTypeLabel(button.buttonType)}</small></span>)}</div></section>
      <section className="panel-section panel-events-section"><div className="panel-section-actions"><SectionTitle title="事件绑定" icon={<Radio size={19} />} />{events.length > 1 && props.availability.eventBatch.enabled && <button data-focus-key="panel-batch" type="button" className="secondary-action" onClick={() => open({ mode: "batch", panel, events: events.map((item) => item.event) }, "panel-batch")}><Settings2 size={16} />批量编辑事件</button>}</div><div className="panel-event-list">{events.map(({ button, event }) => <article key={event.id}><div><strong>{event.alias}</strong><span>{button.alias} · {event.name}</span><small>{targetSummary(event, props.targets)}</small></div><div className="panel-event-actions">{props.availability.eventUpdate.enabled ? <button data-focus-key={"panel-event-" + event.id} type="button" onClick={() => open({ mode: "event", panel, button, event }, "panel-event-" + event.id)}><Pencil size={16} />编辑事件</button> : <span className="panel-readonly"><CircleSlash2 size={16} />当前只读</span>}{props.availability.eventReset.enabled && <button data-focus-key={"panel-reset-" + event.id} type="button" className="danger-action" onClick={() => open({ mode: "reset", panel, button, event }, "panel-reset-" + event.id)}><Trash2 size={16} />清空绑定</button>}</div></article>)}</div></section>
      <section className="panel-section panel-settings"><SectionTitle title="面板设置" icon={<Settings2 size={19} />} /><div className="panel-button-list">{panel.buttons.map((button) => <article key={button.id}><div><strong>{button.alias}</strong><span>{button.name} · 第 {button.index} 键</span></div>{props.availability.configure.enabled ? <button data-focus-key={"panel-alias-" + button.id} type="button" onClick={() => open({ mode: "alias", panel, button }, "panel-alias-" + button.id)}><Pencil size={16} />编辑别名</button> : <span className="panel-readonly"><CircleSlash2 size={16} />{props.availability.configure.message}</span>}</article>)}</div><div className="panel-terminal"><AlertTriangle size={18} /><div><strong>面板测试</strong><span>{reasons.click || "面板测试仅在安装维护应用中提供。"}</span></div></div></section>
    </div>
    {props.feedback && <div className="panel-feedback" aria-live="polite">{props.feedback}</div>}
    {editor && <PanelEditor editor={editor} targets={props.targets} saving={props.saving} onClose={close} onAlias={props.updateAlias} onEvent={props.updateEvent} onBatch={props.updateEvents} onReset={props.resetEvent} />}
  </section>;
}

function PanelEditor({ editor, targets, saving, onClose, onAlias, onEvent, onBatch, onReset }: { editor: Editor; targets: TargetOption[]; saving: boolean; onClose: () => void; onAlias: Props["updateAlias"]; onEvent: Props["updateEvent"]; onBatch: Props["updateEvents"]; onReset: Props["resetEvent"] }) {
  const initialEvent = editor.mode === "event" || editor.mode === "reset" ? editor.event : null; const [alias, setAlias] = useState(editor.mode === "alias" ? editor.button.alias : initialEvent?.alias || ""); const [targetId, setTargetId] = useState(initialEvent?.details[0]?.resId || ""); const [selected, setSelected] = useState(editor.mode === "batch" ? editor.events.map((event) => event.id) : []); const [error, setError] = useState(""); const dialogRef = useRef<HTMLElement>(null); const firstRef = useRef<HTMLInputElement>(null);
  const dirty = editor.mode === "alias" ? alias.trim() !== editor.button.alias : editor.mode === "event" ? alias.trim() !== editor.event.alias || targetId !== editor.event.details[0]?.resId : editor.mode === "batch" ? selected.length > 0 && Boolean(targetId) : false;
  const canSave = editor.mode === "reset" || (editor.mode === "alias" ? dirty && Boolean(alias.trim()) : editor.mode === "event" ? dirty && Boolean(alias.trim()) && Boolean(targetId) : selected.length > 0 && Boolean(targetId));
  const close = () => { if (!saving && (!dirty || window.confirm("放弃尚未保存的面板修改？"))) onClose(); };
  useEffect(() => { const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; window.setTimeout(() => firstRef.current?.focus(), 0); const keydown = (event: KeyboardEvent) => { if (event.key === "Escape") close(); if (event.key !== "Tab" || !dialogRef.current) return; const controls = [...dialogRef.current.querySelectorAll<HTMLElement>("button:not(:disabled), input:not(:disabled), select:not(:disabled)")]; const first = controls[0]; const last = controls.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }; document.addEventListener("keydown", keydown); return () => { document.body.style.overflow = previous; document.removeEventListener("keydown", keydown); }; }, [dirty, saving]);
  const save = async () => { setError(""); try { if (editor.mode === "alias") await onAlias(editor.panel.id, editor.button.id, alias.trim()); if (editor.mode === "event") await onEvent(editor.panel.id, { ...editor.event, alias: alias.trim(), details: [targetDetail(targetId, targets)] }); if (editor.mode === "batch") await onBatch(editor.panel.id, editor.events.filter((event) => selected.includes(event.id)).map((event) => ({ ...event, details: [targetDetail(targetId, targets)] }))); if (editor.mode === "reset") await onReset(editor.panel.id, editor.event.id); onClose(); } catch { setError("保存失败，请检查家庭连接后重试。输入内容已保留。"); } };
  const title = editor.mode === "alias" ? "编辑别名" : editor.mode === "event" ? "编辑事件" : editor.mode === "batch" ? "批量编辑事件" : "清空绑定";
  return <div className="panel-dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><section ref={dialogRef} className="panel-dialog" role="dialog" aria-modal="true" aria-labelledby="panel-dialog-title"><header><div><small>面板设置</small><h3 id="panel-dialog-title">{title}</h3></div><button type="button" className="icon-button" aria-label="关闭面板设置" onClick={close} disabled={saving}><X size={18} /></button></header>{editor.mode === "alias" && <label>按键别名<input ref={firstRef} value={alias} maxLength={24} onChange={(event) => setAlias(event.target.value)} /></label>}{editor.mode === "event" && <><label>事件名称<input ref={firstRef} value={alias} maxLength={24} onChange={(event) => setAlias(event.target.value)} /></label><TargetSelect targets={targets} value={targetId} onChange={setTargetId} /></>}{editor.mode === "batch" && <><fieldset><legend>选择事件</legend><div className="panel-event-options">{editor.events.map((event, index) => <label key={event.id}><input ref={index === 0 ? firstRef : undefined} type="checkbox" checked={selected.includes(event.id)} onChange={() => setSelected((current) => current.includes(event.id) ? current.filter((id) => id !== event.id) : [...current, event.id])} /><span>{event.alias}</span></label>)}</div></fieldset><TargetSelect targets={targets} value={targetId} onChange={setTargetId} /></>}{editor.mode === "reset" && <div className="panel-impact" tabIndex={-1} ref={firstRef as any}><AlertTriangle size={20} /><div><strong>影响摘要</strong><span>将清空“{editor.event.alias}”当前绑定，面板按键本身不会被删除。</span></div></div>}{editor.mode !== "reset" && <div className="panel-impact"><CheckCircle2 size={19} /><div><strong>影响摘要</strong><span>{editor.mode === "batch" ? \`将更新 \${selected.length} 项事件的目标。\` : "仅修改当前选中的面板配置。"}</span></div></div>}{error && <div className="panel-dialog-error" role="alert">{error}</div>}<footer><button type="button" className="secondary-action" onClick={close} disabled={saving}>取消</button><button type="button" className={editor.mode === "reset" ? "danger-primary" : "primary-action"} onClick={() => void save()} disabled={saving || !canSave}>{saving ? <LoaderCircle className="spin" size={17} /> : editor.mode === "reset" ? <Trash2 size={17} /> : <CheckCircle2 size={17} />}{saving ? "正在保存" : editor.mode === "reset" ? "确认清空" : "保存配置"}</button></footer></section></div>;
}

function TargetSelect({ targets, value, onChange }: { targets: TargetOption[]; value: string; onChange: (value: string) => void }) { return <label>绑定目标<select value={value} onChange={(event) => onChange(event.target.value)}><option value="" disabled>请选择绑定目标</option>{targets.map((target) => <option key={target.type + target.id} value={target.id}>{target.type === "scene" ? "情景" : "设备组"} · {target.name}</option>)}</select></label>; }
function targetDetail(targetId: string, targets: TargetOption[]) { return { resId: targetId, typeId: targets.find((target) => target.id === targetId)?.type === "group" ? 2 : 6 }; }
function targetSummary(event: PanelEvent, targets: TargetOption[]) { const id = event.details[0]?.resId; return targets.find((target) => target.id === id)?.name || (id ? "已绑定目标" : "当前目标详情未提供"); }
function buttonTypeLabel(value: number) { return ({ 1: "触控", 2: "单击", 3: "长按", 4: "双击" } as Record<number, string>)[value] || \`类型 \${value || "未知"}\`; }
function SectionTitle({ title, icon }: { title: string; icon: React.ReactNode }) { return <header className="panel-section-title">{icon}<h3>{title}</h3></header>; }
function Fact({ label, value }: { label: string; value: unknown }) { return <div><dt>{label}</dt><dd>{value === undefined || value === "" ? "未提供" : String(value)}</dd></div>; }
function ErrorNotice({ message, retry }: { message?: string; retry: () => Promise<unknown> }) { return message ? <div className="panel-error" role="alert"><AlertTriangle size={18} /><span>{message}</span><button type="button" onClick={() => void retry().catch(() => undefined)}><RotateCcw size={16} />重试</button></div> : null; }
`;
}
