export function switchControllerSource() {
  return `import { useEffect, useMemo, useState } from "react";
import { AlertCircle, BatteryMedium, CheckCircle2, LoaderCircle, ToggleLeft } from "lucide-react";
import { controllerMode, deviceProperties, hasControl, terminalMessage, writeWithReadback, type ControllerDevice, type RefreshDevice } from "./shared";

export function SwitchController({ device, refreshDevice }: { device: ControllerDevice; refreshDevice: RefreshDevice }) {
  const source = deviceProperties(device); const [trusted, setTrusted] = useState(source); const [values, setValues] = useState(source); const [busy, setBusy] = useState("");
  const [feedback, setFeedback] = useState<{ kind: "success" | "error"; message: string } | null>(null); const mode = controllerMode(device);
  const circuits = useMemo(() => { const count = Number(values.numberOfChannels || values.ch_num || 0); const numbered = count > 0 ? Array.from({ length: count }, (_, index) => (index + 1) + "-sp").filter((key) => Object.hasOwn(values, key)) : Object.keys(values).filter((key) => /^[1-6]-sp$/.test(key)).sort((a, b) => Number.parseInt(a) - Number.parseInt(b)); if (numbered.length) return numbered; if (Object.hasOwn(values, "0-sp")) return ["0-sp"]; return ["switchPower", "sp"].filter((key) => Object.hasOwn(values, key)); }, [values]);
  const propertiesKey = JSON.stringify(source);
  useEffect(() => { const next = deviceProperties(device); setTrusted(next); setValues(next); setBusy(""); setFeedback(null); }, [device.id]);
  useEffect(() => { if (busy) return; const next = deviceProperties(device); setTrusted(next); setValues(next); }, [propertiesKey]);
  async function toggle(property: string) { const value = !Boolean(values[property]); setBusy(property); setFeedback(null); setValues((current) => ({ ...current, [property]: value })); try { const refreshed = await writeWithReadback({ device, intent: "device.property.set", parameters: { property, value }, property, expected: value, refreshDevice }); const next = deviceProperties(refreshed); setTrusted(next); setValues(next); setFeedback({ kind: "success", message: "回路状态已更新并完成回读确认。" }); } catch (error) { setValues(trusted); setFeedback({ kind: "error", message: error instanceof Error ? error.message : "回路操作没有完成。" }); } finally { setBusy(""); } }
  return <section className="device-controller switch-controller" aria-labelledby="switch-controller-title"><header className="controller-heading"><span className="controller-icon active"><ToggleLeft size={22} /></span><div><small>{circuits.length ? "开关与继电器" : "无线开关"}</small><h3 id="switch-controller-title">{circuits.length ? circuits.length + " 个可见回路" : "状态与电量"}</h3></div></header>
    {mode !== "write" && <p className="controller-terminal" role="status"><AlertCircle size={17} />{terminalMessage(mode)}</p>}
    {circuits.length ? <div className="circuit-list">{circuits.map((property, index) => { const writable = mode === "write" && hasControl(device, "device.property.set", property); const active = Boolean(values[property]); return <div className="circuit-row" key={property}><span><strong>{property === "switchPower" || property === "sp" ? "总开关" : "回路 " + (index + 1)}</strong><small>{active ? "已开启" : "已关闭"}</small></span><button type="button" role="switch" aria-checked={active} aria-label={(active ? "关闭" : "开启") + "回路 " + (index + 1)} disabled={!writable || Boolean(busy)} onClick={() => void toggle(property)}>{busy === property ? <LoaderCircle className="spin" size={17} /> : <span aria-hidden="true" />}</button></div>; })}</div> : <div className="sensor-reading-grid"><div className="sensor-reading"><BatteryMedium size={20} /><span>电量</span><strong>{String(values.batteryLevel ?? values.battery ?? "-")}%</strong></div><div className="sensor-reading"><ToggleLeft size={20} /><span>按键</span><strong>{String(values.buttonCount ?? "-")}</strong></div></div>}
    <div className={feedback ? "controller-feedback " + feedback.kind : "controller-feedback"} aria-live="polite">{feedback ? <>{feedback.kind === "success" ? <CheckCircle2 size={16} /> : <AlertCircle size={16} />}<span>{feedback.message}</span></> : null}</div></section>;
}
`;
}
